parameters:
- name: name
  displayName: User email or group name.
  type: string
- name: pattern
  displayName: Case-insensitive of a variable group name. All VariableGroups matched are to be used.
  type: string
- name: role
  displayName: Desired user or group role.
  type: string
  values:
    - Administrator
    - Reader
    - User
trigger:
  - main

pool: Selfhosted

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo ${{ parameters.name }}
    echo ${{ parameters.pattern }}
    echo ${{ parameters.role }}
  displayName: 'Run a multi-line script'
