parameters:
- name: name
  displayName: User email or group name.
  type: string
- name: pattern
  displayName: Case-insensitive of a variable group name. All VariableGroups matched are to be used.
  type: string
- name: role
  displayName: Desired user or group role.
  type: string
  values:
    - Administrator
    - Reader
    - User

trigger:
  - none

pool: Selfhosted

container:
  image: ghcr.io/devowlish/az-devops-assigner:0.0.1

steps:

- script: >
    --name ${{ parameters.name }}
    --pattern ${{ parameters.pattern }}
    --role ${{ parameters.role }}
  displayName: 'Assign permissions'
  env:
    AZ_DEVOPS_ORG: $(AZ_DEVOPS_ORG)
    AZ_DEVOPS_PAT: $(AZ_DEVOPS_PAT)
